FROM ubuntu:latest

WORKDIR /app/

COPY scripts/install.sh ./

RUN apt-get update && apt-get -y install build-essential wget zlib1g-dev && bash install.sh

ENV MAVEN_HOME=/usr/lib/apache-maven-3.8.6
ENV JAVA_HOME=/opt/graalvm
ENV GRAALVM_HOME=/opt/graalvm
ENV PATH="${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}"
