FROM golang:1.20 as builder

WORKDIR /app/

COPY atv-cli ./

RUN go build

FROM haroldli/alist-base:hostmode

LABEL MAINTAINER="Har01d"

ENV MEM_OPT="-Xmx512M" ALIST_PORT=5678 INSTALL=hostmode

COPY config/config-host.json /opt/alist/data/config.json

COPY --from=builder /app/atv-cli /

COPY init.sh /
COPY scripts/movie.sh /
COPY scripts/downloadPg.sh /
COPY scripts/downloadZx.sh /
COPY entrypoint.sh /

COPY target/application/ ./

COPY data/tvbox.zip /
COPY data/base_version /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /

COPY data/version data/app_version

EXPOSE 4567 5678

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
