FROM ubuntu:latest

WORKDIR /app/

COPY scripts/install.sh ./

RUN bash install.sh

ENV LANG=en_US.UTF-8
ENV TOOLCHAIN_DIR=/opt/x86_64-linux-musl-native
ENV CC="$TOOLCHAIN_DIR/bin/gcc"
ENV MAVEN_HOME=/opt/maven
ENV JAVA_HOME=/opt/graalvm
ENV GRAALVM_HOME=/opt/graalvm
ENV PATH="${JAVA_HOME}/bin:${MAVEN_HOME}/bin:$TOOLCHAIN_DIR/bin:${PATH}"
