FROM haroldli/alist-base-new:hostmode

LABEL MAINTAINER="Har01d"

ENV MEM_OPT="-Xmx512M"

COPY atv-cli/atv-cli /

COPY init.sh /
COPY movie.sh /
COPY entrypoint.sh /

COPY target/application/ ./

COPY data/version data/app_version

EXPOSE 4567 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
