FROM debian:12-slim

WORKDIR /app/

COPY scripts/install.sh ./

RUN bash install.sh

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV MAVEN_HOME=/opt/maven
ENV JAVA_HOME=/opt/graalvm
ENV GRAALVM_HOME=/opt/graalvm
ENV PATH="${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}"
