FROM haroldli/alist-base:hostmode as base

FROM xiaoyaliu/alist:hostmode

LABEL MAINTAINER="Har01d"

ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

VOLUME /opt/atv/data/

WORKDIR /opt/atv/

COPY index.sh /

COPY --from=base /jre /jre

COPY --from=base /opt/atv/ ./

COPY init.sh /
COPY entrypoint.sh /

COPY target/application/ ./

COPY data/version data/app_version

EXPOSE 8080 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
