FROM golang:1.20 as builder

WORKDIR /app/

COPY atv-cli ./

RUN go build

FROM haroldli/alist:latest

LABEL MAINTAINER="Har01d"

ENV INSTALL=native

VOLUME /opt/atv/data/

WORKDIR /opt/atv/

COPY config/config.json /opt/alist/data/config.json

COPY --from=builder /app/atv-cli /

COPY scripts/index.sh /

COPY init.sh /
COPY scripts/movie.sh /
COPY scripts/downloadPg.sh /
COPY scripts/downloadZx.sh /
COPY entrypoint-native.sh /entrypoint.sh

COPY data/update.sql /
COPY data/countries.json /
COPY data/tvbox.zip /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /
COPY scripts/tgsearch.x86_64 /
COPY scripts/tgsearch.arm64v8 /

COPY target/atv ./

COPY data/version data/app_version

EXPOSE 4567 80 10199

ENTRYPOINT ["/entrypoint.sh"]

CMD ["81", "--spring.profiles.active=production,xiaoya,native"]
