FROM haroldli/alist:hostmode

LABEL MAINTAINER="Har01d"

VOLUME /opt/atv/data/

WORKDIR /opt/atv/

COPY config/config-host.json /opt/alist/data/config.json

COPY atv-cli/atv-cli /
COPY index.sh /

COPY init.sh /
COPY movie.sh /
COPY entrypoint-native.sh /entrypoint.sh

COPY target/atv ./

COPY data/version data/app_version

EXPOSE 4567 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
