package cn.har01d.alist_tvbox;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies the PostgreSQL migration path on a real PostgreSQL container.
 * <p>
 * Why not a full {@code @SpringBootTest}? The app's embedded AList datasource reads
 * {@code /opt/alist/data/config.json} from a hardcoded path and {@code AListLocalService} launches the
 * AList binary subprocess in {@code @PostConstruct}; booting the whole context in a test would also fire
 * the {@code @Scheduled} jobs. None of that is reachable in CI. So this test runs Flyway exactly as the
 * app would on PostgreSQL ({@code {vendor}} -> {@code postgresql} + {@code common}, with the
 * SPI-discovered Java V2/V3) and asserts the parts that a faithful port could get wrong:
 * <ul>
 *   <li>{@code AUTO_INCREMENT} -> {@code GENERATED BY DEFAULT AS IDENTITY} (account/session/x_user)</li>
 *   <li>{@code TINYINT} -> {@code SMALLINT} (driver_account/pan_account/task)</li>
 *   <li>{@code LONGTEXT} -> {@code TEXT} (device.config)</li>
 *   <li>backtick-quoted reserved words -> valid lowercase columns (year/key/value/extend/version)</li>
 *   <li>{@code id_generator} (TableGenerator backing table) present</li>
 *   <li>all of V1..V5 applied</li>
 * </ul>
 * Entity-to-schema correspondence is not re-checked here; it is covered by {@code ddl-auto: validate}
 * on a real PostgreSQL boot (native smoke / deployment) and by the fact that this schema is a faithful,
 * same-named port of the H2 schema the entities already validate against.
 */
@Testcontainers
class PostgreSqlMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    void migrateAndVerifySchema() throws Exception {
        Flyway flyway = Flyway.configure()
                .dataSource(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())
                // Mirrors application.yaml: {vendor} + common SQL, plus current/ for the Java V2/V3
                // migrations (package db.migration.current; current/ has no SQL).
                .locations("classpath:db/migration/postgresql", "classpath:db/migration/common",
                        "classpath:db/migration/current")
                .baselineOnMigrate(true)
                .load();
        // Throws on any SQL error -> V1..V5 must all execute cleanly on PostgreSQL.
        flyway.migrate();

        try (Connection c = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword())) {

            // AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
            for (String t : new String[]{"account", "session", "x_user"}) {
                assertThat(col(c, t, "id").get("is_identity"))
                        .as("%s.id should be an IDENTITY column", t)
                        .isEqualTo("YES");
            }

            // TINYINT -> SMALLINT
            for (String[] tc : new String[][]{
                    {"driver_account", "type"}, {"pan_account", "type"},
                    {"task", "result"}, {"task", "status"}}) {
                assertThat(col(c, tc[0], tc[1]).get("data_type"))
                        .as("%s.%s should be smallint", tc[0], tc[1])
                        .isEqualTo("smallint");
            }

            // LONGTEXT -> TEXT
            assertThat(col(c, "device", "config").get("data_type"))
                    .as("device.config should be text")
                    .isEqualTo("text");

            // double-quoted reserved-word columns exist as lowercase columns
            for (String[] tc : new String[][]{
                    {"movie", "year"}, {"meta", "year"}, {"tmdb", "year"}, {"tmdb_meta", "year"},
                    {"history", "key"}, {"navigation", "value"},
                    {"plugin", "extend"}, {"plugin", "version"},
                    {"plugin_filter", "extend"}, {"plugin_filter", "version"}}) {
                assertThat(col(c, tc[0], tc[1]))
                        .as("%s.%s reserved-word column must exist", tc[0], tc[1])
                        .isNotEmpty();
            }

            // TableGenerator backing table
            assertThat(tableExists(c, "id_generator")).isTrue();

            // All migrations applied (1,4,5,6 SQL + 2,3 Java via the JavaMigration SPI)
            assertThat(appliedVersions(c)).containsExactlyInAnyOrder("1", "2", "3", "4", "5", "6");
        }
    }

    private static Map<String, String> col(Connection c, String table, String column) throws SQLException {
        Map<String, String> m = new LinkedHashMap<>();
        try (PreparedStatement ps = c.prepareStatement(
                "SELECT data_type, is_identity FROM information_schema.columns "
                        + "WHERE table_name = ? AND column_name = ?")) {
            ps.setString(1, table);
            ps.setString(2, column);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    m.put("data_type", rs.getString("data_type"));
                    m.put("is_identity", rs.getString("is_identity"));
                }
            }
        }
        return m;
    }

    private static boolean tableExists(Connection c, String table) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement(
                "SELECT 1 FROM information_schema.tables WHERE table_name = ?")) {
            ps.setString(1, table);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    private static List<String> appliedVersions(Connection c) throws SQLException {
        List<String> versions = new ArrayList<>();
        try (PreparedStatement ps = c.prepareStatement(
                "SELECT version FROM flyway_schema_history WHERE success = true ORDER BY installed_rank");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                versions.add(rs.getString("version"));
            }
        }
        return versions;
    }
}
