FROM haroldli/alist-base:hostmode

LABEL MAINTAINER="Har01d"

ENV INSTALL=native-host NATIVE=true

WORKDIR /opt/atv/

COPY config/alist-host.json /alist.json

COPY scripts/index.sh /

COPY docker/scripts/ /docker/scripts/

COPY data/update.sql /
COPY data/tvbox.zip /
COPY data/115.index.zip /
COPY data/index.share.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

EXPOSE 4567 5678

VOLUME ["/www/static"]

ENTRYPOINT ["/docker/scripts/entrypoint-native.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,native,host"]
