FROM haroldli/alist-base:latest

LABEL MAINTAINER="Har01d"

ENV INSTALL=native

WORKDIR /opt/atv/

COPY config/alist.json /

COPY entrypoint-native.sh /entrypoint.sh
COPY scripts/index.sh /
COPY scripts/init.sh /

COPY data/tvbox.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

EXPOSE 4567 5244

ENTRYPOINT ["/entrypoint.sh"]

CMD ["81", "--spring.profiles.active=production,docker"]
