FROM haroldli/alist-base:latest

LABEL MAINTAINER="Har01d"

ENV INSTALL=native NATIVE=true

WORKDIR /opt/atv/

COPY config/alist.json /

COPY scripts/index.sh /

COPY docker/scripts/ /docker/scripts/

COPY data/update.sql /
COPY data/tvbox.zip /
COPY data/115.index.zip /
COPY data/index.share.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

EXPOSE 4567 80

VOLUME ["/www/static"]

ENTRYPOINT ["/docker/scripts/entrypoint-native.sh"]

CMD ["81", "--spring.profiles.active=production,xiaoya,native"]
