FROM haroldli/alist:latest

LABEL MAINTAINER="Har01d"

ENV INSTALL=native

WORKDIR /opt/atv/

COPY config/alist.json /

COPY scripts/index.sh /

COPY init.sh /
COPY scripts/movie.sh /
COPY scripts/downloadPg.sh /
COPY scripts/downloadZx.sh /
COPY entrypoint-native.sh /entrypoint.sh

COPY data/update.sql /
COPY data/tvbox.zip /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

EXPOSE 4567 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["81", "--spring.profiles.active=production,xiaoya,native"]
