FROM haroldli/alist-base:hostmode

LABEL MAINTAINER="Har01d"

ENV INSTALL=native-host

WORKDIR /opt/atv/

COPY config/alist-host.json /alist.json

COPY scripts/index.sh /

COPY entrypoint-native.sh /entrypoint.sh
COPY init.sh /

COPY data/update.sql /
COPY data/tvbox.zip /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

EXPOSE 4567 5678

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,native,host"]
