FROM haroldli/alist-base-new:hostmode

LABEL MAINTAINER="Har01d"

ENV MEM_OPT="-Xmx512M"

COPY config/alist-host.json /alist.json

COPY entrypoint.sh /
COPY init.sh /

COPY data/tvbox.zip /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/data.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/base_version /

COPY target/application/ ./

COPY data/version /app_version

EXPOSE 4567 5678

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
