FROM haroldli/alist-base:hostmode

LABEL MAINTAINER="Har01d"

ARG TARGETARCH

ENV MEM_OPT="-Xmx1024M" ALIST_PORT=5678 INSTALL=hostmode

COPY config/alist-host.json /alist.json

COPY entrypoint.sh /
COPY init.sh /
COPY scripts/tg-provider-runtime.sh /tg-provider-runtime.sh
RUN chmod +x /tg-provider-runtime.sh

COPY data/tvbox.zip /
COPY data/base_version /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /

COPY build/tg-provider/linux-${TARGETARCH}/tg-provider /usr/local/bin/tg-provider
RUN chmod +x /usr/local/bin/tg-provider
COPY target/application/ ./

COPY data/version /app_version

EXPOSE 4567 5678

ENTRYPOINT ["/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
