FROM haroldli/alist-base:hostmode

LABEL MAINTAINER="Har01d"

ENV MEM_OPT="-Xmx1024M" ALIST_PORT=5678 INSTALL=hostmode

COPY config/alist-host.json /alist.json

COPY docker/scripts/ /docker/scripts/

COPY data/tvbox.zip /
COPY data/115.index.zip /
COPY data/base_version /
COPY data/index.share.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /

COPY target/application/ ./

COPY data/version /app_version

EXPOSE 4567 5678

VOLUME ["/www/static"]

ENTRYPOINT ["/docker/scripts/entrypoint.sh"]

CMD ["5233", "--spring.profiles.active=production,xiaoya,host"]
