ARG TAG=latest

FROM haroldli/java:17 AS corretto-jdk

FROM haroldli/alist:${TAG}

LABEL MAINTAINER="Har01d"

ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY data/update.sql /

COPY --from=corretto-jdk /jre $JAVA_HOME

WORKDIR /opt/atv/

COPY scripts/index.sh /
COPY scripts/h2-2.1.214.jar /

COPY target/dependencies/ ./
COPY target/snapshot-dependencies/ ./
COPY target/spring-boot-loader/ ./
