CREATE TABLE IF NOT EXISTS PUBLIC.PLUGIN_FILTER
(
    ID              INTEGER not null
        primary key,
    NAME            CHARACTER VARYING(255) not null,
    URL             CHARACTER VARYING not null
        constraint UK_PLUGIN_FILTER_URL
            unique,
    ENABLED         BOOLEAN default TRUE not null,
    SORT_ORDER      INTEGER not null,
    STAGES          CHARACTER VARYING(255),
    EXTEND          CHARACTER VARYING,
    ERROR_STRATEGY  CHARACTER VARYING(32),
    SOURCE_NAME     CHARACTER VARYING(255) not null,
    CONTENT         CHARACTER VARYING,
    VERSION         INTEGER,
    LAST_CHECKED_AT TIMESTAMP WITH TIME ZONE,
    LAST_ERROR      CHARACTER VARYING
);

CREATE INDEX IF NOT EXISTS IDX_PLUGIN_FILTER_SORT_ORDER ON PUBLIC.PLUGIN_FILTER (SORT_ORDER);
