-- 为过滤器增加插件作用范围；旧数据统一迁移为全局生效
ALTER TABLE PUBLIC.PLUGIN_FILTER ADD COLUMN IF NOT EXISTS PLUGIN_SCOPE CHARACTER VARYING(32) DEFAULT 'all' NOT NULL;
ALTER TABLE PUBLIC.PLUGIN_FILTER ADD COLUMN IF NOT EXISTS PLUGIN_IDS CHARACTER VARYING;

UPDATE PUBLIC.PLUGIN_FILTER SET PLUGIN_SCOPE = 'all' WHERE PLUGIN_SCOPE IS NULL OR PLUGIN_SCOPE = '';
UPDATE PUBLIC.PLUGIN_FILTER SET PLUGIN_IDS = '' WHERE PLUGIN_IDS IS NULL;
