FROM ubuntu:latest

WORKDIR /app/

COPY install.sh ./

RUN bash install.sh

ENV MAVEN_HOME=/opt/maven
ENV JAVA_HOME=/opt/graalvm
ENV GRAALVM_HOME=/opt/graalvm
ENV PATH="${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}"
