CREATE TABLE IF NOT EXISTS PUBLIC.ACCOUNT
(
    ID                     INTEGER auto_increment
        primary key,
    ACCESS_TOKEN           CHARACTER VARYING,
    ACCESS_TOKEN_TIME      TIMESTAMP WITH TIME ZONE,
    AUTO_CHECKIN           BOOLEAN not null,
    CHECKIN_DAYS           INTEGER not null,
    CHECKIN_TIME           TIMESTAMP WITH TIME ZONE,
    CHUNK_SIZE             INTEGER,
    CLEAN                  BOOLEAN default FALSE,
    CONCURRENCY            INTEGER,
    MASTER                 BOOLEAN default FALSE,
    NICKNAME               CHARACTER VARYING(255),
    OPEN_ACCESS_TOKEN      CHARACTER VARYING,
    OPEN_ACCESS_TOKEN_TIME TIMESTAMP WITH TIME ZONE,
    OPEN_TOKEN             CHARACTER VARYING,
    OPEN_TOKEN_TIME        TIMESTAMP WITH TIME ZONE,
    REFRESH_TOKEN          CHARACTER VARYING(255),
    REFRESH_TOKEN_TIME     TIMESTAMP WITH TIME ZONE,
    SHOW_MY_ALI            BOOLEAN not null,
    USE_PROXY              BOOLEAN default FALSE
);

CREATE TABLE IF NOT EXISTS PUBLIC.ALIAS
(
    NAME     CHARACTER VARYING(255) not null,
    ALIAS    CHARACTER VARYING(255),
    MOVIE_ID INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.ALIST_ALIAS
(
    ID      INTEGER not null
        primary key,
    CONTENT CHARACTER VARYING,
    PATH    CHARACTER VARYING(255)
        constraint UK_QV7FIH8LC5TFV13RWPOJUDMJH
            unique
);

CREATE TABLE IF NOT EXISTS PUBLIC.CONFIG_FILE
(
    ID      INTEGER auto_increment
        primary key,
    CONTENT CHARACTER VARYING,
    DIR     CHARACTER VARYING(255),
    NAME    CHARACTER VARYING(255),
    PATH    CHARACTER VARYING(255)
        constraint UK_BVC79DNFQPOLSFVI3NJX8NB50
            unique
);

CREATE TABLE IF NOT EXISTS PUBLIC.DEVICE
(
    ID     INTEGER not null
        primary key,
    CONFIG CHARACTER VARYING,
    IP     CHARACTER VARYING(255),
    NAME   CHARACTER VARYING(255),
    TYPE   INTEGER not null,
    UUID   CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.DRIVER_ACCOUNT
(
    ID            INTEGER not null
        primary key,
    ADDITION      CHARACTER VARYING,
    CONCURRENCY   INTEGER,
    COOKIE        CHARACTER VARYING,
    DISABLED      BOOLEAN default FALSE,
    FOLDER        CHARACTER VARYING(255),
    MASTER        BOOLEAN not null,
    NAME          CHARACTER VARYING(255),
    PASSWORD      CHARACTER VARYING(255),
    SAFE_PASSWORD CHARACTER VARYING(255),
    TOKEN         CHARACTER VARYING,
    TYPE          TINYINT,
    USE_PROXY     BOOLEAN default FALSE,
    USERNAME      CHARACTER VARYING(255),
    check ("TYPE" BETWEEN 0 AND 26)
);

CREATE TABLE IF NOT EXISTS PUBLIC.EMBY
(
    ID             INTEGER not null
        primary key,
    CLIENT_NAME    CHARACTER VARYING(255),
    CLIENT_VERSION CHARACTER VARYING(255),
    DEVICE_ID      CHARACTER VARYING(255),
    DEVICE_NAME    CHARACTER VARYING(255),
    NAME           CHARACTER VARYING(255),
    "order"        INTEGER,
    PASSWORD       CHARACTER VARYING(255),
    URL            CHARACTER VARYING(255),
    USER_AGENT     CHARACTER VARYING(255),
    USERNAME       CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.HISTORY
(
    ID          INTEGER not null
        primary key,
    CID         INTEGER not null,
    CREATE_TIME BIGINT  not null,
    DURATION    BIGINT  not null,
    ENDING      BIGINT  not null,
    EPISODE     INTEGER not null,
    EPISODE_URL CHARACTER VARYING,
    "key"       CHARACTER VARYING,
    OPENING     BIGINT  not null,
    POSITION    BIGINT  not null,
    REV_PLAY    BOOLEAN not null,
    REV_SORT    BOOLEAN not null,
    SCALE       INTEGER not null,
    SPEED       REAL    not null,
    VOD_FLAG    CHARACTER VARYING(255),
    VOD_NAME    CHARACTER VARYING(255),
    VOD_PIC     CHARACTER VARYING(255),
    VOD_REMARKS CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.ID_GENERATOR
(
    ENTITY_NAME CHARACTER VARYING(255) not null
        primary key,
    NEXT_ID     BIGINT
);

CREATE TABLE IF NOT EXISTS PUBLIC.INDEX_TEMPLATE
(
    ID            INTEGER not null
        primary key,
    CREATED_TIME  TIMESTAMP WITH TIME ZONE,
    DATA          CHARACTER VARYING,
    NAME          CHARACTER VARYING(255),
    SCHEDULE_TIME CHARACTER VARYING(255),
    SCHEDULED     BOOLEAN default FALSE,
    SCRAPE        BOOLEAN default FALSE,
    SITE_ID       INTEGER,
    SLEEP         INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.JELLYFIN
(
    ID             INTEGER not null
        primary key,
    CLIENT_NAME    CHARACTER VARYING(255),
    CLIENT_VERSION CHARACTER VARYING(255),
    DEVICE_ID      CHARACTER VARYING(255),
    DEVICE_NAME    CHARACTER VARYING(255),
    NAME           CHARACTER VARYING(255),
    "order"        INTEGER,
    PASSWORD       CHARACTER VARYING(255),
    URL            CHARACTER VARYING(255),
    USER_AGENT     CHARACTER VARYING(255),
    USERNAME       CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.META
(
    ID       INTEGER auto_increment,
    NAME     CHARACTER VARYING(255),
    PATH     CHARACTER VARYING(255),
    SCORE    INTEGER,
    SITE_ID  INTEGER,
    TIME     TIMESTAMP,
    TM_ID    INTEGER,
    TMDB_ID  INTEGER,
    TYPE     CHARACTER VARYING(255),
    "year"   INTEGER,
    MOVIE_ID INTEGER,
    TID      INTEGER,
    DISABLED BOOLEAN default FALSE
);

CREATE TABLE IF NOT EXISTS PUBLIC.MOVIE
(
    ID          INTEGER not null
        primary key,
    ACTORS      CHARACTER VARYING(255),
    COUNTRY     CHARACTER VARYING(255),
    COVER       CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    DIRECTORS   CHARACTER VARYING(255),
    EDITORS     CHARACTER VARYING(255),
    GENRE       CHARACTER VARYING(255),
    LANGUAGE    CHARACTER VARYING(255),
    NAME        CHARACTER VARYING(255),
    DB_SCORE    CHARACTER VARYING(255),
    "year"      INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.NAVIGATION
(
    ID        INTEGER not null
        primary key,
    NAME      CHARACTER VARYING(255),
    "order"   INTEGER,
    PARENT_ID INTEGER not null,
    RESERVED  BOOLEAN default FALSE,
    SHOW      BOOLEAN default TRUE,
    TYPE      INTEGER not null,
    "value"   CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.PAN_ACCOUNT
(
    ID        INTEGER not null
        primary key,
    COOKIE    CHARACTER VARYING,
    FOLDER    CHARACTER VARYING(255),
    MASTER    BOOLEAN not null,
    NAME      CHARACTER VARYING(255),
    TOKEN     CHARACTER VARYING(255),
    TYPE      TINYINT,
    USE_PROXY BOOLEAN default FALSE,
    check ("TYPE" BETWEEN 0 AND 26)
);

CREATE TABLE IF NOT EXISTS PUBLIC.PIK_PAK_ACCOUNT
(
    ID                   INTEGER not null
        primary key,
    MASTER               BOOLEAN not null,
    NICKNAME             CHARACTER VARYING(255),
    PASSWORD             CHARACTER VARYING(255),
    PLATFORM             CHARACTER VARYING(255),
    REFRESH_TOKEN_METHOD CHARACTER VARYING(255),
    USERNAME             CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.PLAY_URL
(
    ID   INTEGER           not null
        primary key,
    PATH CHARACTER VARYING not null,
    SITE INTEGER           not null,
    TIME TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS PUBLIC.SETTING
(
    NAME     CHARACTER VARYING(255) not null
        primary key,
    "svalue" CHARACTER VARYING
);

CREATE TABLE IF NOT EXISTS PUBLIC.SHARE
(
    ID        INTEGER not null
        primary key,
    COOKIE    CHARACTER VARYING,
    FOLDER_ID CHARACTER VARYING(255),
    PASSWORD  CHARACTER VARYING(255),
    PATH      CHARACTER VARYING(255)
        constraint UK_OS4CMBWQBBQ9U3PTGJED0RVG8
            unique,
    SHARE_ID  CHARACTER VARYING(255),
    TEMP      BOOLEAN default FALSE,
    TIME      TIMESTAMP WITH TIME ZONE,
    TYPE      INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.SITE
(
    ID         INTEGER not null
        primary key,
    DISABLED   BOOLEAN not null,
    FOLDER     CHARACTER VARYING(255),
    INDEX_FILE CHARACTER VARYING(255),
    NAME       CHARACTER VARYING(255),
    "order"    INTEGER,
    PASSWORD   CHARACTER VARYING(255),
    SEARCHABLE BOOLEAN not null,
    TOKEN      CHARACTER VARYING(255),
    URL        CHARACTER VARYING(255),
    "version"  INTEGER,
    XIAOYA     BOOLEAN default FALSE
);

CREATE TABLE IF NOT EXISTS PUBLIC.SUBSCRIPTION
(
    ID       INTEGER not null
        primary key,
    NAME     CHARACTER VARYING(255),
    OVERRIDE CHARACTER VARYING,
    SID      CHARACTER VARYING(255),
    SORT     CHARACTER VARYING(255),
    URL      CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS PUBLIC.TASK
(
    ID           INTEGER not null
        primary key,
    CREATED_TIME TIMESTAMP WITH TIME ZONE,
    DATA         CHARACTER VARYING,
    END_TIME     TIMESTAMP WITH TIME ZONE,
    ERROR        CHARACTER VARYING(255),
    NAME         CHARACTER VARYING(255),
    RESULT       TINYINT,
    START_TIME   TIMESTAMP WITH TIME ZONE,
    STATUS       TINYINT,
    SUMMARY      CHARACTER VARYING(255),
    TASK_TYPE    CHARACTER VARYING(255),
    UPDATED_TIME TIMESTAMP WITH TIME ZONE,
    check ("RESULT" BETWEEN 0 AND 2),
    check ("STATUS" BETWEEN 0 AND 2),
    check ("TASK_TYPE" IN ('INDEX', 'VALIDATE_INDEX', 'SCRAPE', 'SYNC_META', 'DOWNLOAD'))
);

CREATE TABLE IF NOT EXISTS PUBLIC.TENANT
(
    ID      INTEGER                not null
        primary key,
    EXCLUDE CHARACTER VARYING,
    INCLUDE CHARACTER VARYING,
    NAME    CHARACTER VARYING(255) not null
        constraint UK_DCXF3KSI0GYN1TIEEQ0ID96LM
            unique
);

CREATE TABLE IF NOT EXISTS PUBLIC.TMDB
(
    ID          INTEGER not null
        primary key,
    ACTORS      CHARACTER VARYING(255),
    COUNTRY     CHARACTER VARYING(255),
    COVER       CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    DIRECTORS   CHARACTER VARYING(255),
    EDITORS     CHARACTER VARYING(255),
    GENRE       CHARACTER VARYING(255),
    LANGUAGE    CHARACTER VARYING(255),
    NAME        CHARACTER VARYING(255),
    SCORE       CHARACTER VARYING(255),
    TMDB_ID     INTEGER,
    TYPE        CHARACTER VARYING(255),
    "year"      INTEGER
);

CREATE TABLE IF NOT EXISTS PUBLIC.TMDB_META
(
    ID      INTEGER not null
        primary key,
    NAME    CHARACTER VARYING(255),
    PATH    CHARACTER VARYING(255)
        constraint UK_7PF1QHPPEEX7NG1TV3KY1G2L2
            unique,
    SCORE   INTEGER,
    SITE_ID INTEGER,
    TID     INTEGER,
    TIME    TIMESTAMP WITH TIME ZONE,
    TM_ID   INTEGER,
    TYPE    CHARACTER VARYING(255),
    "year"  INTEGER,
    TMDB_ID INTEGER,
    constraint FK7C376Q76DCR01QHU3C06U0SOS
        foreign key (TMDB_ID) references PUBLIC.TMDB
);

CREATE TABLE IF NOT EXISTS PUBLIC."USERS"
(
    ID           INTEGER auto_increment
        primary key,
    CREATED_TIME TIMESTAMP WITH TIME ZONE,
    PASSWORD     CHARACTER VARYING(255),
    USERNAME     CHARACTER VARYING(255)
);
