ALTER TABLE PUBLIC.PLUGIN
    ADD COLUMN IF NOT EXISTS LOCAL_PATH CHARACTER VARYING(255);

UPDATE PUBLIC.PLUGIN
SET LOCAL_PATH = CONCAT('/www/plugins/', ID, '.txt')
WHERE LOCAL_PATH IS NULL;

ALTER TABLE PUBLIC.PLUGIN
    ALTER COLUMN LOCAL_PATH SET NOT NULL;
